Distributions and Tests
miking-lang/miking-dppl pull request #77
Opened 2021-12-07 13:04 UTC by vsenderov

This PR contains new distributions, fixes to existing distributions, and the unit testing framework now works with the new style of macros.

New and refactored distributions:
- Student's t distribution with one parameter (all platforms). OMP and CPU use C++ STD, GPU uses the derivation from Gaussian and Xi-squared
- 3 parameter Student's distribution now uses the single parameter Student's t distribution (it is a different distribution compared to before)
- NormalInverseGammaNormal uses the new three parameter Student's t-distribution
- LinearNormalInverseGammaNormal (mean and variance can be rescaled and shifted)

Fixes:
- renamed `sample_normalInverseGammaNormal` to `normalInverseGammaNormal`
- renamed `score_normalInverseGammaNormal` to `normalInverseGammaNormalScore`
- same refactoring for `gammaExponential`
- can use now the OBSERVE macro with `gammaExponential` and `normalInverseGammaNormal`

Tests:
- unit tests use the new style of macros (FIRST_BBLOCK, etc.)
- unit tests are split in three - for CPU, OMP, and GPU

    unit_tests.sh
    unit_tests_omp.sh 
    unit_tests_gpu.sh

- new distributions are covered by the unit tests now

2021-12-13 15:26 UTC, dlunde requested changes

2021-12-13 15:26 UTC, dlunde commented on rootppl/tests/.Rhistory
> +1/rgamma(10000, shape = 1, rate = 0.2)
This file should not be commited.

2021-12-13 15:26 UTC, dlunde commented
Hi Viktor, looks good. But, remove the generated `.Rhistory` file I mentioned above.

2021-12-14 11:49 UTC, dlunde approved these changes

2021-12-15 17:06 UTC, vsenderov commented
Renamed:

 `student_t_classic` => `student_t`
 `student_t` => `linearStudent_t`
 `chi_squared` => `chiSquared`

unit tests pass.

2021-12-21 21:09 UTC, merged